#!/bin/sh

# create business cards by stacking a template with text (prepared with Inkscape and Hershey text plugin) with a
# random "alien letter" symbol generated by alien_letter.py

vpype begin grid 2 5 -d 85mm 55mm \
  script alien_letter.py \
  scale -o 0 0 --to 1.2cm 1.2cm \
  translate 0.5cm 0.8cm \
  read bc_template.svg \
end \
write -p a4 -c business_cards.svg
