[device.hp7475a]
name = "hp7475a"
plotter_unit_length = "0.02488mm"
pen_count = 6

[[device.hp7475a.paper]]
name = "a4"
paper_size = ["297mm", "210mm"]
x_range = [0, 11040]
y_range = [0, 7721]
y_axis_up = true
origin_location = ["10mm", "206mm"]
set_ps = 4

[[device.hp7475a.paper]]
name = "a3"
paper_size = ["420mm", "297mm"]
x_range = [0, 16158]
y_range = [0, 11040]
y_axis_up = true
origin_location = ["15mm", "287mm"]
set_ps = 0

[[device.hp7475a.paper]]
name = "a"
aka_names = ["ansi_a", "letter"]
paper_size = ["11in", "8.5in"]
x_range = [0, 10365]
y_range = [0, 7962]
y_axis_up = true
origin_location = ["10mm", "211mm"]
set_ps = 4

[[device.hp7475a.paper]]
name = "b"
aka_names = ["ansi_b", "tabloid"]
paper_size = ["17in", "11in"]
x_range = [0, 16640]
y_range = [0, 10365]
y_axis_up = true
origin_location = ["15mm", "287mm"]
set_ps = 0

[device.calcomp_designmate]
name = "designmate"
plotter_unit_length = "0.02488mm"
pen_count = 8

[[device.calcomp_designmate.paper]]
name = "a4"     # Will always be loaded in Landscape oriebtaion in the Designmate
aka_names = ["A4"]
paper_size = ["297mm", "210mm"]
x_range = [0, 11040]
y_range = [0, 7721]
y_axis_up = true
origin_location = ["12mm", "198mm"]
set_ps = 0

[[device.calcomp_designmate.paper]]
name = "a3"  # As loaded in portrait orientaion in the plotter. Does not affect drawing orientaion, only page margins
aka_names = ["A3"]
paper_size = ["420mm", "297mm"]
x_range = [0, 15207]
y_range = [0, 10853]
y_axis_up = true
origin_location = ["12mm", "272mm"]
set_ps = 0

[[device.calcomp_designmate.paper]]
name = "a3l"      # For A3 paper loaded in landscape orientaion in the plotter. Does not affect drawing orientaion, only page margins
aka_names = ["A3l", "a3landscape", "A3landscape"]
paper_size = ["420mm", "297mm"]
x_range = [0, 15722]
y_range = [0, 10300]
y_axis_up = true
origin_location = ["12mm", "285mm"]
set_ps = 0
