name: Windows Installer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  windows-installer:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1.1.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install dependencies
      run: poetry install
    - name: Run PyInstaller
      run: |
        poetry run pyinstaller --noconfirm --onedir \
          --name vpype --icon="scripts/vpype.ico" \
          --add-data="vpype/hpgl_devices.toml;vpype" \
          --additional-hooks-dir=scripts/hooks \
          scripts/run_vpype.py
    - name: Create NSIS installer
      uses: joncloud/makensis-action@v3.3
      with:
        script-file: scripts\installer_win.nsi
        arguments: "/V4 /DVERSION=$VERSION"
    - uses: actions/upload-artifact@v2
      with:
        path: dist/vpype-$VERSION-setup.exe
